# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/project_sl/FPGA/project/Flappy_Bird.runs/synth_1/FlappyBird.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k160tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project_sl/FPGA/project/Flappy_Bird.cache/wt [current_project]
set_property parent.project_path D:/project_sl/FPGA/project/Flappy_Bird.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/project_sl/FPGA/project/Flappy_Bird.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_skull.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_beginning.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_rooftop.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_pipe.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_skull_2.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_pipe_2.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_green_pipe.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_bright_beginning.coe
add_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/output_pipe_2_2.coe
add_files D:/project_sl/FPGA/project/output_pipe_taller.coe
read_verilog -library xil_defaultlib {
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/Crash_Detect.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/DisplayScore.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/Draw_Bird.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/Draw_Tubes.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/imports/FPGA/Exp12/task_2.srcs/sources_1/new/LED_DRV.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/Loadgen.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/imports/FPGA/Exp6/DispNumber_sch.srcs/sources_1/imports/exp6/MyMC14495.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/Myload.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/ScoreDisplay.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/SignalFrequency.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/VGAFrequency.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/VGA_Bitgen.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/VGA_Controller.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/cal_divmum.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/clk_100.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/imports/imports/project_sl/FPGA/Exp11/task3.srcs/sources_1/imports/sources_1/imports/FPGA/Exp7/ScoreBoard.srcs/sources_1/new/clkdiv.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/clkdiv.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/imports/new/counter4b.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/hour_first.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/hour_second.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/keyboard.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/music_beep.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/music_mem.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/pbdebounce.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/random_gen.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/rom_0.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/rom_1.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/rom_2.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/rom_3.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/new/rom_4.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/second_first.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/second_second.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/shift_reg8b.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/shift_reg9b.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/speed_ctrl.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/sources_1/new/top.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/new/wave_gen.v
  D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/imports/Flappy-Bird-master/FlappyBird.v
}
read_ip -quiet D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/project_sl/FPGA/project/Flappy_Bird.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/project_sl/FPGA/project/Flappy_Bird.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/project_sl/FPGA/project/Flappy_Bird.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all d:/project_sl/FPGA/project/Flappy_Bird.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet D:/project_sl/FPGA/project/Flappy_Bird.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/project_sl/FPGA/project/Flappy_Bird.gen/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project_sl/FPGA/project/Flappy_Bird.srcs/constrs_1/new/K7.xdc
set_property used_in_implementation false [get_files D:/project_sl/FPGA/project/Flappy_Bird.srcs/constrs_1/new/K7.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/project_sl/FPGA/project/Flappy_Bird.srcs/utils_1/imports/synth_1/FlappyBird.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top FlappyBird -part xc7k160tffg676-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FlappyBird.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file FlappyBird_utilization_synth.rpt -pb FlappyBird_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
