/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module shift_reg8b (
  input [7:0] Pin,
  input SL,
  input Sin,
  input clk,
  output S,
  output finish1
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  assign s0 = Pin[7];
  assign s1 = Pin[6];
  assign s2 = Pin[5];
  assign s3 = Pin[4];
  assign s4 = Pin[3];
  assign s5 = Pin[2];
  assign s6 = Pin[1];
  assign s7 = Pin[0];
  Mux_2x1 Mux_2x1_i0 (
    .sel( SL ),
    .in_0( Sin ),
    .in_1( s7 ),
    .out( s22 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s22 ),
    .C( clk ),
    .Q( s20 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( SL ),
    .in_0( s20 ),
    .in_1( s6 ),
    .out( s21 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s21 ),
    .C( clk ),
    .Q( s18 )
  );
  Mux_2x1 Mux_2x1_i4 (
    .sel( SL ),
    .in_0( s18 ),
    .in_1( s5 ),
    .out( s19 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s19 ),
    .C( clk ),
    .Q( s16 )
  );
  Mux_2x1 Mux_2x1_i6 (
    .sel( SL ),
    .in_0( s16 ),
    .in_1( s4 ),
    .out( s17 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s17 ),
    .C( clk ),
    .Q( s14 )
  );
  Mux_2x1 Mux_2x1_i8 (
    .sel( SL ),
    .in_0( s14 ),
    .in_1( s3 ),
    .out( s15 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s15 ),
    .C( clk ),
    .Q( s12 )
  );
  Mux_2x1 Mux_2x1_i10 (
    .sel( SL ),
    .in_0( s12 ),
    .in_1( s2 ),
    .out( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( s13 ),
    .C( clk ),
    .Q( s10 )
  );
  Mux_2x1 Mux_2x1_i12 (
    .sel( SL ),
    .in_0( s10 ),
    .in_1( s1 ),
    .out( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i13 (
    .D( s11 ),
    .C( clk ),
    .Q( s8 )
  );
  Mux_2x1 Mux_2x1_i14 (
    .sel( SL ),
    .in_0( s8 ),
    .in_1( s0 ),
    .out( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( s9 ),
    .C( clk ),
    .Q( S )
  );
  assign finish1=s8&s10&s12&s14&s16&s18&s20;
endmodule
