/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module counter_4bit (
  input clk,
  output RC,
  output QA,
  output QB,
  output QC,
  output QD
);
  wire QD_temp;
  wire QC_temp;
  wire QB_temp;
  wire QA_temp;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( clk ),
    .Q( QA_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s1 ),
    .C( clk ),
    .Q( QB_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s2 ),
    .C( clk ),
    .Q( QC_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s3 ),
    .C( clk ),
    .Q( QD_temp ),
    .\~Q ( s3 )
  );
  assign RC = (QD_temp & QC_temp & QB_temp & QA_temp);
  assign s0 = (QA_temp ^ (QB_temp & QC_temp & QD_temp));
  assign s1 = (QB_temp ^ (QC_temp & QD_temp));
  assign s2 = (QC_temp ^ QD_temp);
  assign QA = QA_temp;
  assign QB = QB_temp;
  assign QC = QC_temp;
  assign QD = QD_temp;
endmodule
